import { ExactField } from '@/constants/data-enums'
import { isoToDisplayDate } from '@/utils/luxon'
import { truncateString } from '@/utils/common'
import type { ColumnProps } from '@/constants/types-interfaces'

/**
 * Field display properties for columns in QTables. There should be one for every class field for
 * classes that pair with a database table.
 * @param exactField
 * @returns Object with properties for QTable columns
 */
export function getExactFieldColumnProps(exactField: ExactField): ColumnProps {
  /**
   * @see
   * MUST ADD NEW EXACT FIELDS BELOW
   */
  return {
    [ExactField.ID]: {
      name: ExactField.ID,
      label: 'Id',
      align: 'left',
      sortable: true,
      required: true,
      field: (row: any) => row[ExactField.ID],
      format: (val: string) => val,
    },
    [ExactField.CREATED_DATE]: {
      name: ExactField.CREATED_DATE,
      label: 'Created Date',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.CREATED_DATE],
      format: (val: string) => isoToDisplayDate(val),
    },
    [ExactField.NAME]: {
      name: ExactField.NAME,
      label: 'Name',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.NAME],
      format: (val: string) => truncateString(val),
    },
    [ExactField.DESCRIPTION]: {
      name: ExactField.DESCRIPTION,
      label: 'Description',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.DESCRIPTION],
      format: (val: string) => truncateString(val),
    },
    [ExactField.PARENT_ID]: {
      name: ExactField.PARENT_ID,
      label: 'Parent',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.PARENT_ID],
      format: (val: string) => val,
    },
    [ExactField.NOTE]: {
      name: ExactField.NOTE,
      label: 'Note',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.NOTE],
      format: (val: string) => truncateString(val),
    },
    [ExactField.ACTIVITY_STATUS]: {
      name: ExactField.ACTIVITY_STATUS,
      label: 'Status',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.ACTIVITY_STATUS],
      format: (val: string) => val,
    },
    [ExactField.RECORD_STATUS]: {
      name: ExactField.RECORD_STATUS,
      label: 'Status',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.RECORD_STATUS],
      format: (val: string) => val,
    },
    [ExactField.EXERCISE_TRACKS]: {
      name: ExactField.EXERCISE_TRACKS,
      label: 'Tracks',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.EXERCISE_TRACKS],
      format: (val: string) => val,
    },
    [ExactField.EXERCISE_IDS]: {
      name: ExactField.EXERCISE_IDS,
      label: 'Exercise Ids',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.EXERCISE_IDS],
      format: (val: string) => val,
    },
    [ExactField.FINISHED_DATE]: {
      name: ExactField.FINISHED_DATE,
      label: 'Finished Date',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.FINISHED_DATE],
      format: (val: string) => isoToDisplayDate(val),
    },
    [ExactField.EXERCISE_RECORD_IDS]: {
      name: ExactField.EXERCISE_RECORD_IDS,
      label: 'Record Ids',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.EXERCISE_RECORD_IDS],
      format: (val: string) => val,
    },
    [ExactField.MEASUREMENT_TYPE]: {
      name: ExactField.MEASUREMENT_TYPE,
      label: 'Type',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.MEASUREMENT_TYPE],
      format: (val: string) => val,
    },
    [ExactField.PARENT_MEASUREMENT_TYPE]: {
      name: ExactField.PARENT_MEASUREMENT_TYPE,
      label: 'Parent Type',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.PARENT_MEASUREMENT_TYPE],
      format: (val: string) => val,
    },
    [ExactField.MEASUREMENT_VALUE]: {
      name: ExactField.MEASUREMENT_VALUE,
      label: 'Value',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.MEASUREMENT_VALUE],
      format: (val: number) => val,
    },
    [ExactField.WEIGHT_LBS_PER_SET]: {
      name: ExactField.WEIGHT_LBS_PER_SET,
      label: 'Weight (lbs)',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.WEIGHT_LBS_PER_SET],
      format: (val: number[]) => val,
    },
    [ExactField.REPS_PER_SET]: {
      name: ExactField.REPS_PER_SET,
      label: 'Reps',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.REPS_PER_SET],
      format: (val: number[]) => val,
    },
    [ExactField.DISTANCE_MILES_PER_SET]: {
      name: ExactField.DISTANCE_MILES_PER_SET,
      label: 'Distance (miles)',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.DISTANCE_MILES_PER_SET],
      format: (val: number[]) => val,
    },
    [ExactField.DURATION_MINUTES_PER_SET]: {
      name: ExactField.DURATION_MINUTES_PER_SET,
      label: 'Duration (minutes)',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.DURATION_MINUTES_PER_SET],
      format: (val: number[]) => val,
    },
    [ExactField.KEY]: {
      name: ExactField.KEY,
      label: 'Key',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.KEY],
      format: (val: string) => val,
    },
    [ExactField.VALUE]: {
      name: ExactField.VALUE,
      label: 'Value',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.VALUE],
      format: (val: boolean | string | number) => val,
    },
    [ExactField.SEVERITY]: {
      name: ExactField.SEVERITY,
      label: 'Severity',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.SEVERITY],
      format: (val: string) => val,
    },
    [ExactField.DETAILS]: {
      name: ExactField.DETAILS,
      label: 'Details',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.DETAILS],
      format: (val: string) => truncateString(val),
    },
    [ExactField.MESSAGE]: {
      name: ExactField.MESSAGE,
      label: 'Messages',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.MESSAGE],
      format: (val: string) => truncateString(val),
    },
    [ExactField.STACK]: {
      name: ExactField.STACK,
      label: 'Stack',
      align: 'left',
      sortable: true,
      required: false,
      field: (row: any) => row[ExactField.STACK],
      format: (val: string) => truncateString(val),
    },
  }[exactField]
}
